runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/apps/portfolio/index.html
    upload: dist/apps/portfolio/index.html
  - url: /
    static_dir: dist/apps/portfolio
options:
 logging: CLOUD_LOGGING_ONLY
skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
